### ISSUE TITLE
CRUD Support in vlite

### ISSUE THREAD

**Issue by nurse-the-code** [sdan/vlite#16]
Hey there,

First off, I'm thoroughly impressed by the work on `vlite`! The performance is top-notch and the ease with which we can add and read data is commendable.

However, upon exploring the codebase, it appears that only the 'Create' and 'Read' operations of a full CRUD (Create, Read, Update, Delete) lifecycle are currently supported. Unless I'm mistaken, there seems to be no straightforward way to 'Update' or 'Delete' data within `vlite`. 

The addition of full CRUD support would exponentially enhance the usability of `vlite`. Here's why:

1. **Flexibility**: Full CRUD operations allow for more versatile data management. Users can alter or remove data as their requirements change.
2. **Data Consistency**: The 'Update' feature ensures that data remains accurate and up-to-date, fostering better decision-making.
3. **Data Quality**: The 'Delete' operation enables users to maintain data quality by removing irrelevant, duplicate, or outdated data.
4. **Optimized Storage**: Removing unnecessary data optimizes storage use, leading to a more efficient database.
5. **Interoperability**: Many developers are accustomed to working with full-featured databases that support all CRUD operations. Having these in `vlite` makes the transition easier and enhances developer experience.

Could you please confirm whether 'Update' and 'Delete' operations are indeed not supported at this time? If so, I would strongly advocate for their inclusion in future updates.

Thanks for your attention and the excellent work you're doing!

**Comment by Codie-Petersen** [comment]
@nurse-the-code 
"However, upon exploring the codebase, it appears that only the 'Create' and 'Read' operations of a full CRUD (Create, Read, Update, Delete) lifecycle are currently supported. Unless I'm mistaken, there seems to be no straightforward way to 'Update' or 'Delete' data within vlite."

I don't know if there is a Update or Delete function, but the code is definitely setup to support it. His "id" system could easily be used to delete an index. 

I'm curious though, what is your idea of "The 'Update' feature ensures that data remains accurate and up-to-date, fostering better decision-making." I'm not sure in which context people might be updating memories. Just curious, as I might run across the same need in the future as well.

But I like your suggestions. 

BTW, most VDBs do not support CRUD because they are not fully deterministic recall. VLite seems to be unique in the fact it even tracks entry ids. On the other hand, you need to separately track which IDs and the content associated with it for the ids to even be useful. Using a hash of the stripped content with no punctuation or capitalization might be a good way to associate the data though.

You should drop some ideas in here, so he has something to work with.

**Comment by Codie-Petersen** [comment]
@nurse-the-code 
As a side note, the creator looks like the might be busy with other projects, which I totally get. I'm creating a fork in which I'll be incorporating these methods.

**Comment by sdan** [comment]
fixed in the next release 0.2.0
